name = "NeptuneAILogger"
uuid = "edd09736-da86-44b6-b465-b626e6fb8c8b"
authors = ["Anthony Corso <anthonycorso92@gmail.com>"]
version = "0.1.0"

[deps]
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[weakdeps]
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"

[compat]
FluxTraining = "0.3"
PackageExtensionCompat = "1"
PythonCall = "0.9"
julia = "1"

[extras]
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Test", "Plots"]