name: Format suggestions
on:
  pull_request:
jobs:
  code-style:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v2